[package]
name = "holochain_container_api"
version = "0.0.2"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
holochain_cas_implementations = { path = "../cas_implementations" }
holochain_core = { path = "../core" }
holochain_core_types = { path = "../core_types" }
holochain_net = { path = "../net" }
futures-preview = "0.3.0-alpha.11"
tempfile = "3"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
toml = "0.4.8"
boolinator = "2.4"
tiny_http = "0.6.0"
jsonrpc-ws-server = { git = "https://github.com/paritytech/jsonrpc" }
petgraph = "0.4.13"

[dev-dependencies]
test_utils = { path = "../test_utils"}
clap = "2"
structopt = "0.2"
tempfile = "3"
